#!/usr/bin/env bash
#this script takes a file and server and transfers the file to the server
#at the location specified
if [[ "$#" -lt 3 ]]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    #given ./0-transfer_file $1 - some_page.html $2 - 8.8.8.8
    #$3 - sylvain $4 - /vagrant/private_key (key location)
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi
