#!/usr/bin/env bash
#this script installs nginx on a server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/test.com
sudo ln -s /etc/nginx/sites-available/test.com /etc/nginx/sites-enabled/
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i 's/server_name _;/server_name winikoff.tech;\n'\
     'rewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent'\
     /etc/nginx/sites-available/test.com
sudo service nginx restart
