#!/usr/bin/env bash
#this script installs nginx on a server
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World" | sudo tee /var/www/html/index.html
search_string="^\tlocation / {"
to_replace="\tlocation /redirect_me {\n\treturn 301 \$scheme://www.youtube.com/watch?v=exD-oGci-9M;\n\t}\n\tlocation / {"
sudo sed -i "s@${search_string}@${to_replace}@" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
replace2="\terror_page 404 /error404.html;\n\tlocation / {"
sudo sed -i "s@${search_string}@${replace2}@" /etc/nginx/sites-available/default
sudo service nginx restart
