#!/usr/bin/env bash
#this script will install haproxy load balancer
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo ENABLED=1 | sudo tee -a /etc/default/haproxy
echo "
            frontend http_front
            bind *:80
            stats uri /haproxy/stats
            default_backend custom_backend

            backend custom_backend
            balance roundrobin
            server 2677-web-01 3.84.114.230:80 check
            server 2677-web-02 18.234.237.222:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
